### ISSUE TITLE
Weather Underground no longer provides free API keys

### ISSUE THREAD

**Issue by davidneedham** [stefanheule/graphite#1]
Thanks for creating this watch face. I went to add a weather API key from https://www.wunderground.com/weather/api/ and this is what it says:

>To improve our services and enhance our relationship with our users, we will no longer provide free weather API keys as part of our program. If you have been directed to download our Weather Underground free API key by a third party provider, please contact your vendor for resolution.

So I added the API key for Dark Sky instead. So far (6 hrs later) I'm still not getting rain or low/high, so I'm not sure if that's actually working either. If you'd like, I can open a new issue for that.

**Comment by stefanheule** [comment]
Sorry for the long delay.  I am still using this watchface, and yeeah, Weather Underground unfortunately no longer works.  Dark Sky however should work, that's what I'm using now.  What watch do you have?  Is it still not working for you?

**Comment by davidneedham** [comment]
No worries! Thanks for replying. I have a Pebble Time. I just tried again for the first time since opening the issue. It seems to be working now. 👍
