### ISSUE TITLE
No graph support for OpenWeatherMap

### ISSUE THREAD

**Issue by realEnzeta** [stefanheule/graphite#3]
I know this face for an obscure early smartwatch hasn't been updated in years but with the Dark Sky API shut down there is no way to get the precipitation graph anymore. I'm fairly sure OWM now supports hourly precipitation and any help from anyone to get weather working again would be helpful.

**Comment by stefanheule** [comment]
I'm still wearing my pebble every day and using this watch face! I've been equally annoyed not having rain forecasts, but have been too lazy to fix it. Your bug report is probably enough motivation to fix this. Let me take a look what we can do here.

**Comment by stefanheule** [comment]
Alright, I just released v1.5, which has hourly rain forecast (and also low/high temps for the current day, that was missing too). You can download it from https://stefanheule.com/graphite/. Let me know if this isn't working for you.

**Comment by realEnzeta** [comment]
Installed and runs with no issues on my Time, high/low now works but I haven't seen the precipitation graph yet (no rain for over 24h on openweather). I've been using this face for around two years now (coming from Timestyle) and it's easily my favourite even without full weather support.

**Comment by stefanheule** [comment]
Awesome. Rain should work too, there's plenty of that where I'm at and I can confirm it's showing up on the watchface. But let me know if it doesn't work for you :)
